### PR TITLE
Set the priorityClassName, topologySpreadConstraints in op-deployment

### PR DESCRIPTION
**Pull request by jhohertz**
op deployment wasn't actually using the overprovisioning priorityclass

Also added ability to set the topologySpreadConstraints while I was here.

Fixed a paste-o that I noticed in the readme while I was adding the new field.

### CODE REVIEW

**Review by grieshaber — APPROVED** [review]
LGTM, thanks for the PR!

**Comment by grieshaber** [comment]
One thing missing is the updated Chart version. We haven't automated the update yet, so it would be great if you could just bump it to i'd say 0.5.1 or 0.6.0, as you introduced the topologySpreadConstraints "feature".

**Review by grieshaber — CHANGES_REQUESTED** [review]
One thing missing is the updated Chart version. We haven't automated the update yet, so it would be great if you could just bump it to i'd say 0.5.1 or 0.6.0, as you introduced the topologySpreadConstraints "feature".

**Comment by achetronic** [comment]
Hello @grieshaber I have the same problem, so if you are fine with it, I can do it :)

**Comment by grieshaber** [comment]
Closed in favor of #15

**Pull request closed without merging**
